apiVersion: apps/v1
kind: Deployment
metadata:
  name: anime-recommender
spec:
  replicas: 2
  selector:
    matchLabels:
      app: anime-recommender
  template:
    metadata:
      labels:
        app: anime-recommender
    spec:
      containers:
        - name: anime-recommender-container
          image: gcr.io/unique-ellipse-477612-c7/anime-recommender:latest
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: anime-recommender-service
spec:
  type: LoadBalancer
  selector:
    app: anime-recommender
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
